sudo: required
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
cache: cargo
services:
  - docker
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker build -t ikrelln/ikrelln:sqlite .
    fi

