[package]
name = "ikrelln"
version = "0.1.0"
authors = ["François Mockers <mockersf@gmail.com>"]
build = "build.rs"

[dependencies]
log = "*"
fern = "*"
chrono = "*"
mime = "*"
time = "*"

clap = "*"

uuid = { version = "0.5", features = ["serde", "v4"] }

serde = "*"
serde_derive = "*"

futures = "*"
env_logger = "*"
actix = "*"
actix-web = "*"

failure = "*"

diesel = { version = "1.1.0", features = ["sqlite"] }
